### ISSUE TITLE
Java API for NextCloud?

### ISSUE THREAD

**Issue by sachinkariyattin** [nextcloud/android-library#133]
Hello,

I am planning to integrate NextCloud with my Java application. I was wondering if there is a Java API for NextCloud similar to this. I assume this android library can be tweaked to implement something like that. Has anyone tried it? Are there any implementations? 

I could find one such implementation here [https://github.com/a-schild/nextcloud-java-api](https://github.com/a-schild/nextcloud-java-api), but it has not method to download a file.

Please let me know.

**Comment by tobiasKaminsky** [comment]
Nice idea, but I am not aware of anything like that.
In the end the main communication is webdav.
But to not duplicate work I would try to enhance the linked java lib.
