### ISSUE TITLE
bump minSdkVersion to 19

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android-library#1566]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

Currently the lib as mindSDk set to 14 which is blocking a lot of library updates that need at least 19 to compile again.

Given our clients will move to 26 as their min SDK I think we can savely bump the lib to 19.

**Comment by tobiasKaminsky** [comment]
Fixed with https://github.com/nextcloud/android-library/pull/1576
