### ISSUE TITLE
How to configure Proguard for Android Client library

### ISSUE THREAD

**Issue by gerritbeuze** [nextcloud/android-library#160]
Hi,
I’m using the Nextcloud Android library to add Nextcloud support to an android app using Android Studio. I’m having trouble configuring Proguard. When I run with minifyEnabled false all is fine, but with minifyEnabled true I get lots of Proguard related warnings and error. For example:

com.owncloud.android.lib.common.ExternalLink$$Parcelable: can’t find superclass or interface org.parceler.ParcelWrapper

library class org.apache.commons.codec.binary.BinaryCodec extends or implements program class org.apache.commons.codec.BinaryDecoder

org.apache.jackrabbit.webdav.server.AbstractWebdavServlet: can’t find referenced method ‘int getContentLength()’ in program class org.apache.jackrabbit.webdav.WebdavRequest

I can run with disabling the warings , for example
-dontwarn com.owncloud.android.lib.**
etc.
But then the app crashes as soon as a client completes.

I have tried copying the Proguard.cfg settings from the Nextcloud client app on Github, but that does not make a difference.

Any idea how to configure Proguard to make this work?

Thanks in advance,

Gerrit Beuze

**Comment by gerritbeuze** [comment]
In case anyone else stumbles upon this, here's a section of the Proguard config that makes it work in my case. Note: the -keep,allowshrinking is required, just ignoring the warnings was not enough.
```
# Nextcloud
-keep,allowshrinking class com.owncloud.android.** { *; }
-keep,allowshrinking class org.apache.jackrabbit.webdav.** { *; }
-keep,allowshrinking class org.apache.commons.codec.** { *; }
-keep,allowshrinking class org.apache.commons.logging.** { *; }
-keep,allowshrinking class org.parceler.** { *; }
-keep,allowshrinking class org.slf4j.** { *; }

#ignore nextcloud related warnings
-dontwarn com.owncloud.android.lib.**
-dontwarn org.apache.jackrabbit.webdav.**
-dontwarn org.apache.commons.codec.**
-dontwarn org.apache.commons.logging.**
-dontwarn org.slf4j.**

-dontskipnonpubliclibraryclasses

-keepclasseswithmembernames class * {
    native <methods>;
}

-keepclasseswithmembers class * {
    public <init>(android.content.Context, android.util.AttributeSet);
}

-keepclasseswithmembers class * {
    public <init>(android.content.Context, android.util.AttributeSet, int);
}

-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

-keep class * implements android.os.Parcelable {
  public static final android.os.Parcelable$Creator *;
}

-keepattributes InnerClasses
#end nextcloud
```

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky what do you think? I'd say it'd be nice to have this in the lib's documentation :)

**Comment by tobiasKaminsky** [comment]
We have not enabled proguard on client app.
I am not sure if the setting there is working at all….

Until we have a good reason to use proguard, I would rather remove it completely.
(People need to use it, can still find this issue)

**Comment by AndyScherzinger** [comment]
Okay, fine by me

**Comment by tobiasKaminsky** [comment]
Then I'll close this, but as said, it can still be found via search.
