### ISSUE TITLE
What is undocumented UploadRemoteFileOperation param fileLastModifTimestamp

### ISSUE THREAD

**Issue by gerritbeuze** [nextcloud/android-library#162]
Hi,

The documentation 
https://docs.nextcloud.com/server/13/developer_manual/android_library/examples.html
does not mention the 4th param in the constructor 
`UploadRemoteFileOperation(String localPath, String remotePath, String mimeType, String fileLastModifTimestamp);`
What should this be ? How should a long File.lastModified be formatted to math this?

When I simply pass "" or null, I get a 500 internal server error reply - which is converted to INSTANCE_NOT _CONFIGURED, but all other calls (download, list directory , remoteFileInformation etc all work as designed)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can you answer this question? :)

**Comment by gerritbeuze** [comment]
I tried a few things and it seems to be the unix time stamp (seconds since 1 jan 1970) which I calculate as
`Long.toString(File.lastModified() / 1000);`
