### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by PhieF** [nextcloud/android-library#195]
Hi,

I keep having 403 forbidden exception when using this code on some servers (perhaps the ones with reverse proxies)

but the nextcloud app works when using old authentication method. Any ideas why ? 
Thanks !
```

OwnCloudClient client = OwnCloudClientFactory.createOwnCloudClient(
                    Uri.parse("https://server"),
                    getContext(),
                    true);
            client.setCredentials(
                    OwnCloudCredentialsFactory.newBasicCredentials("username", "password")
            );

            ExistenceCheckRemoteOperation operation = new ExistenceCheckRemoteOperation("/", false);
            RemoteOperationResult result = operation.execute(client);

            if (operation.wasRedirected()) {
                RedirectionPath redirectionPath = operation.getRedirectionPath();
                String permanentLocation = redirectionPath.getLastPermanentLocation();
                result.setLastPermanentLocation(permanentLocation);
            }

            Log.d("connectdebug",result.getLogMessage());
            Log.d("connectdebug ",""+(result.isServerFail() || result.isException()));
            return result.isSuccess();

```

**Comment by tobiasKaminsky** [comment]
What is the old authentication method?
Can you recheck if this only happens on server with reverse proxy?

**Comment by PhieF** [comment]
Hi
Well it's on one of my users server, and this pne is behind a reverse proxy. Yesterday i've implemented login with a geberated password, so new login method, and I have the same issue. The strangest thing is that I'm doing the exact same thing as the nextcloud app. I've built the nextcloud app on my computer and this one is working on his server.

**Comment by tobiasKaminsky** [comment]
Do you see something in server log?

@nextcloud/server-triage do you have any idea what/why reverse proxy might mess this up?

**Comment by tobiasKaminsky** [comment]
Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by PhieF** [comment]
This user provided me credentials you can find here
https://github.com/PhieF/CarnetNextcloud/issues/3#issuecomment-435392616

thank you very much

**Comment by PhieF** [comment]
I can't access it anymore, it wasn't my server, but I will ask it again ! :)

**Comment by mdallaire** [comment]
The latest version of the Android client (0.13 I think) works well for me with 2FA using the app password now.

**Comment by tobiasKaminsky** [comment]
Good to hear, then I'll close this.
Please feel free to reopen.
