### ISSUE TITLE
Failed to resolve error

### ISSUE THREAD

**Issue by arch1m0r** [nextcloud/android-library#200]
Hi,

I am using Android Studio and I want to use the library. I updated my root gradle file with:
maven { url "https://jitpack.io" }

And added this in my app gradle file:
implementation 'com.github.nextcloud:android-library:1.1.0'

I also tried -SNAPSHOT or master but this does not work:
Failed to resolve: com.github.nextcloud:android-library:1.1.0

How to get the library then?

**Comment by AndyScherzinger** [comment]
Hi @arch1m0r I should work just like you've written. Sometimes jitpack has some hickups and can't resolve dependencies but ingeneral it works. Else you can compare it to the Nextcloud client gradle config: https://github.com/nextcloud/android/blob/master/build.gradle

**Comment by arch1m0r** [comment]
Sorry I made a mistake:
The maven url function has to be inside the allprojects environment (I had it inside the buildscript environment):

`// Top-level build file where you can add configuration options common to all sub-projects/modules.`

`buildscript {`
    
`    repositories {`
    `    google()`
 `      jcenter()`
 `   }`
 `   dependencies {`
   `     classpath 'com.google.gms:google-services:4.0.1'`
   `     classpath 'com.android.tools.build:gradle:3.2.0'`
        

    `    // NOTE: Do not place your application dependencies here; they belong`
   `     // in the individual module build.gradle files`
`    }`
`}`

`allprojects {`
`    repositories {`
    `    google()`
  `      jcenter()`
    `    maven { url "https://jitpack.io" }`
  `  }`
`}`

`task clean(type: Delete) {`
   ` delete rootProject.buildDir`
`}`

**Comment by AndyScherzinger** [comment]
@arch1m0r so everything working fine for you now? :)

**Comment by arch1m0r** [comment]
Yes. I have to figure out how the library works - but that's something different :) But there is a nice documentation so I will try my best thank you!

**Comment by AndyScherzinger** [comment]
@NKnuelle take a lock at https://github.com/stefan-niedermann/nextcloud-notes @stefan-niedermann who already created a fine Nextcloud Notes Android app :)
