### ISSUE TITLE
UploadFileRemoteOperation cannot be solved

### ISSUE THREAD

**Issue by NKnuelle** [nextcloud/android-library#207]
I added the library via gradle with this:
`implementation 'com.github.nextcloud:android-library:1.2.0'`

I try to build the functionality of the sample client into my app but Android Studio does not resolve the correct classes. The names of some classes have changed some days ago and leads to problems. I try to import this (like in the SampleClient):
`UploadFileRemoteOperation`

But Android Studio/the compiler only knows this:
`import com.owncloud.android.lib.resources.files.UploadRemoteFileOperation;`

I already rebuild the project/reopened Android Studio but the problem remains..

**Comment by tobiasKaminsky** [comment]
This is intended.
All Operation are now called RemoteOperation to distinguish them from other Operations.

Thanks for the info that there is something wrong with the SampleClient.

**Comment by tobiasKaminsky** [comment]
Ah, sorry, I read it wrong.
1.2.0 is the latest release with the old name scheming.
If you want to use the newest one, just use -SNAPSHOT:
'com.github.nextcloud:android-library:master-SNAPSHOT'

With the next android files release in ~2 months, there will also be a new stable library version including the new name schema.

**Comment by NKnuelle** [comment]
Ahh my fault sorry. Works now. Didn't see that the releases are just tags not branches.
