### ISSUE TITLE
Android-SingleSignOn and this library

### ISSUE THREAD

**Issue by PhieF** [nextcloud/android-library#216]
Hi, 
is this library compatible with that one https://github.com/nextcloud/Android-SingleSignOn

?

Because I can't login once I've authorized the account with singlesignon, using url, username  and token as password in android-library

thanks !

**Comment by tobiasKaminsky** [comment]
This library is indepentent from the SSO approach.
This library provides all of the basic operation you can do on the server, like upload, download, delete, …

The SSO is somewhat different: an user installs NC files app (main app), which includes this library. 
Any other app can now use the SSO from the NC files app, to do requests on behalf of the NC files app (after the user authenticated it).
