### ISSUE TITLE
Add me to the repository

### ISSUE THREAD

**Issue by mario** [nextcloud/android-library#29]
### Actual behavior
I am not a member of the repository, can't commit, push or review.

### Expected behavior
I should be a member of the repository, should be able to commit, push and review.
 
### Steps to reproduce
1. Buy a cookie
2. Check the list of repository users
3. See that I'm missing

**Comment by AndyScherzinger** [comment]
will be covered by https://github.com/nextcloud/android/issues/542 automagically :)
