### ISSUE TITLE
Cannot use ReadRemoteFolderOperation

### ISSUE THREAD

**Issue by burningthumb** [nextcloud/android-library#321]
I'm not sure why, maybe you are using an old version of the ownCloud library, but when I try to use ReadRemoteFolderOperation as in:

`ReadRemoteFolderOperation refreshOperation = new ReadRemoteFolderOperation(FileUtils.PATH_SEPARATOR);
`

I get the error

> cannot resolve symbol 'ReadRemoteFolderOperation'

**Comment by tobiasKaminsky** [comment]
We changed at some point the naming scheme:
now all operations in library will end with RemoteOperation.

In your case it is ReadFolderRemoteOperation.
