### ISSUE TITLE
GetRemoteUserInfoOperation fails with OpenLDAP users

### ISSUE THREAD

**Issue by alexcustos** [nextcloud/android-library#35]
By default the internal username is taken from the UUID attribute. GetRemoteUserInfoOperation is trying to request UserInfo by login and fails with exception related to JSON parser.

**Comment by mario** [comment]
Do you have an error? :)

**Comment by alexcustos** [comment]
Yes, but it's useless. The problem will be the same if 'credentials.getUsername()' (in very beginning of the run method) be replaced with a random string. I've already fix my openLDAP instance, but I intend to sort out this problem. So I just leave it here as a reminder to myself.

**Comment by alexcustos** [comment]
It's all looks like this feature is not released yet. I've just found one spelling mistake:
`public static final int MINIMUM_SELF_API = 0x11000200;` this constant must be set to `0x0B000200` in file OwnCloudVersion.java. So as long as the server v11.0.2.0 is not released yet, all other problems not problems at all :)

**Comment by mario** [comment]
:P 

Will fix the typo, thanks :)

**Comment by mario** [comment]
So stable version of the app (the one in Play store) works?

**Comment by alexcustos** [comment]
It does not work. The key of the problem is to get LDAP User UUID (ID) by this call `/ocs/v1.php/cloud/user`. The call `/ocs/v1.php/cloud/users/ + credentials.getUsername()` fails with error "The requested user could not be found". But I can't use first approach because server not returning NODE_QUOTA yet, so GetRemoteUserInfoOperation fails in anyway.

**Comment by mario** [comment]
Fixed, and should be in next release.
