### ISSUE TITLE
when I use other RemoteOperation , it happens "FILE_NOT_FOUND'

### ISSUE THREAD

**Issue by swepthong** [nextcloud/android-library#445]
DownloadFileRemoteOperation,GetUserInfoRemoteOperation,ReadFolderRemoteOperation were  OK.
when I use other RemoteOperation , such as "ReadTrashbinFolderRemoteOperation", or "SearchRemoteOperation"  ,    it happens "FILE_NOT_FOUND'

ReadTrashbinFolderRemoteOperation: Synchronized /: Local file does not exist
result: RemoteOperationResult(mSuccess=false, mHttpCode=404, mHttpPhrase=Not Found, mException=null, mCode=FILE_NOT_FOUND, getLogMessage=Local file does not exist) 

what's  the problem?

**Comment by swepthong** [comment]
I  found   client.getUserId = null

**Comment by swepthong** [comment]
when i set userId   , it was ok  ?

is  UserId   equals  userName ?    How to get It

**Comment by tobiasKaminsky** [comment]
userId is the internal id for the user.
You can get it when querying /ocs/v1.php/cloud/user
