### ISSUE TITLE
Support Nextcloud notifications

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android-library#54]
see discussion here https://github.com/nextcloud/android/issues/559
add support to the lib to fetch notifications from the server.
Notifications are on the following API https://github.com/nextcloud/notifications/blob/master/docs/ocs-endpoint-v2.md

Work has been started on https://github.com/nextcloud/android-library/tree/notifications

**Comment by mario** [comment]
Done, so closing.
