### ISSUE TITLE
ReadFileVersionsRemoteOperation always ends up with file not found

### ISSUE THREAD

**Issue by Toprakete** [nextcloud/android-library#690]
Steps to reproduce
Request versions with ReadFileVersionsRemoteOperation
Execute request
Result is always not success with file not found
Expected behaviour
result should be success and deliver list of versions of the given file
Actual behaviour
Always no success because of File not found
Can you reproduce this problem on https://try.nextcloud.com?
Yes

Environment data
Android version: 10

Device model: Huawei Honor View 10

Client creation:
mClient = OwnCloudClientFactory.createOwnCloudClient(serverUri, ctx, true);
mClient.setCredentials(
OwnCloudCredentialsFactory.newBasicCredentials(
XXXXXX,
YYYYYY
)
);

Request:

ReadFileVersionsRemoteOperation rop = new ReadFileVersionsRemoteOperation(mHelpFileId) // mHelpFileId="121427";
rop.execute(mClient, this, mHandler);

Perhaps this helps:
In Browser the response for this request has a first not found response. the second response is server code 200 and has data. Seems that library just sees the not found of the first response.

<d:multistatus
xmlns:d="DAV:"
xmlns:s="http://sabredav.org/ns"
xmlns:oc="http://owncloud.org/ns"
xmlns:nc="http://nextcloud.org/ns">
<d:response>
<d:href>/remote.php/dav/versions/XXXXX/versions/121427/</d:href>
<d:propstat>
<d:prop>
<d:getcontentlength/>
<d:getcontenttype/>
<d:getlastmodified/>
</d:prop>
<d:status>HTTP/1.1 404 Not Found</d:status>
</d:propstat>
</d:response>
<d:response>
<d:href>/remote.php/dav/versions/XXXXX/versions/121427/1611152051</d:href>
<d:propstat>
<d:prop>
<d:getcontentlength>11617184</d:getcontentlength>
<d:getcontenttype>application/pdf</d:getcontenttype>
<d:getlastmodified>Wed, 20 Jan 2021 14:14:11 GMT</d:getlastmodified>
</d:prop>
<d:status>HTTP/1.1 200 OK</d:status>
</d:propstat>
</d:response>
</d:multistatus>

**Comment by tobiasKaminsky** [comment]
The response is multistatus, which allows to have properties that are not set (404).
But you see that there is a proper response (<d:href>/remote.php/dav/versions/XXXXX/versions/121427/1611152051</d:href>)

I wrote a test #694, which confirms that it is working.
Maybe it helps you to see how to work with it.
If not, please feel free to ask here for help :)

**Comment by Toprakete** [comment]
Hi, thx for you fast reply. Tried with synch execute function and result is the same:
I tried following code:

new AsyncTask<Void, Void, Void>() {
            @Override
            protected Void doInBackground(Void... voids) {
                ReadFileVersionsRemoteOperation rop = new ReadFileVersionsRemoteOperation(mHelpFileId);
                RemoteOperationResult res = rop.execute(mClient);
                if (res.isSuccess()) {
                    Log.d(TAG,"OK");
                } else {
                    Log.d(TAG,"Error: "+res.getHttpPhrase());
                }
                return null;
            }
        }.execute();

Result is :
"HelpUpdater: Error: Not Found"

![image](https://user-images.githubusercontent.com/11770949/130050060-bed5d316-ebf5-43b4-80c2-2a093000f4c1.png)

What do I wrong?
br

**Comment by Toprakete** [comment]
The mHelpFileId comes from here:

`if (operation instanceof ReadFolderRemoteOperation) {
                // check for help.pdf
                for (Object obj : result.getData()) {
                    RemoteFile rf = (RemoteFile) obj;
                    String t = rf.getLocalId();
                    String z = rf.getEtag();
                    if (rf.getMimeType().equalsIgnoreCase("dir")) continue;
                    if (rf.getRemotePath().endsWith("help.pdf")) {
                        mHelpFileId = rf.getLocalId();
                        break;
                    }
                }
                if (!TextUtils.isEmpty(m_helpFileId)) {
                    // request versions
                    loadOnlineHelpVersion();
                }
            }`

**Comment by Toprakete** [comment]
When I step through the HttpMethodBase class during the ReadFolderRemoteOperation I got a statusline:
HTTP/1.1 207 Multi-Status
When I step during the Version request I got a statusline:
HTTP/1.1 404 Not Found

Have I the correct client?
I create it with
```
mClient = OwnCloudClientFactory.createOwnCloudClient(serverUri, ctx, true);
mClient.setCredentials(
        OwnCloudCredentialsFactory.newBasicCredentials(
                ProjectDBFileHandler.NC_USERNAME,
                ProjectDBFileHandler.NC_PASSWORD
        )
);
```
As in the SampleClinet done.

The HttpMethodBase class is part of the apache common httpclient, but on project page it is told that OkHttpClient is used.
Perhaps this the failure?

**Comment by tobiasKaminsky** [comment]
Can you verify that you use the correct id?
In above it would be 121427 as seen in browser info?
Has this file a version available in sidebar in browser?

**Comment by Toprakete** [comment]
Yes
![image](https://user-images.githubusercontent.com/11770949/130190720-2ac584b6-ad17-4c07-a7d3-8a006d70e407.png)

I will create a empty new project and check again. I checked with the demo account of nextcloud and same happens, so maybe one of the other libraries influence this

**Comment by Toprakete** [comment]
Made a new empty Activity project
```

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.3.1'
    implementation 'com.google.android.material:material:1.4.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.0'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
    implementation "commons-httpclient:commons-httpclient:3.1@jar"
    implementation 'com.github.nextcloud:android-library:2.7.0'
}
```

```
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);
    Uri serverUri = Uri.parse(NC_SERVER_URL);
    mHandler = new Handler();
    mClient = OwnCloudClientFactory.createOwnCloudClient(serverUri, this, true);
    mClient.setCredentials(
            OwnCloudCredentialsFactory.newBasicCredentials(
                    NC_USERNAME,
                    NC_PASSWORD
            )
    );

    new AsyncTask<Void, Void, Void>() {
        @Override
        protected Void doInBackground(Void... voids) {
            ReadFileVersionsRemoteOperation rop = new ReadFileVersionsRemoteOperation("121427");
            RemoteOperationResult res = rop.execute(mClient);
            if (res.isSuccess()) {
                Log.d(TAG,"OK");
            } else {
                Log.d(TAG,"Error: "+res.getHttpPhrase());
            }
            return null;
        }
    }.execute();
}
```
Same behaviour.

**Comment by tobiasKaminsky** [comment]
Can you check in ReadFileVersionsRemoteOperation:79 if client.getUserId() is set correct?
It must be the internal user id of Nextcloud, when you add the user.
I suspect that this is not set and thus 404 returns.

**Comment by Toprakete** [comment]
Ah, yes that's right!
![image](https://user-images.githubusercontent.com/11770949/130212317-d963896b-cf85-43fc-adde-40ce60f10a20.png)
How to get this?

**Comment by tobiasKaminsky** [comment]
You can retrieve it via GetUserInfoRemoteOperation

**Comment by Toprakete** [comment]
UnsupportedOperationException("Not used anymore"), seems only NextCloudClient has implemented this.
What's the current client? NextCloudClient or OwnCloudClient?
Where is an examplke for NextCloudClient? Sample Client uses OwnCloudClient.

**Comment by Toprakete** [comment]
GetActivitiesRemoteOperation works, hope I will get this what I want with that. Thx for your patient. br

**Comment by tobiasKaminsky** [comment]
NextcloudClient is what we will soon use everywhere, but migration is slow.
