### ISSUE TITLE
Timeout when assembling large file uploads

### ISSUE THREAD

**Issue by minfaer** [nextcloud/android-library#696]
As reported to the android-app repository in nextcloud/android#5609, uploading large files fails at 100% by timeout if the server takes too long assembling them. This results in an endless loop of retries and conflicts.

This can be fixed by increasing the read-timeout of the move-method that does the assembly in the chunk-upload. I tested setting the timeout to a flat 15 minutes similarly to what was done to version 1 of the library in #19. However, maybe that timeout should scale with the filesize only for files larger than some limit (like 100mb) and be left alone otherwise?

If desired, I can submit a pr for either solution.

**Comment by minfaer** [comment]
As the question came up in the aforementioned issue: the desktop-client adjusts the time-out depending on filesize in [this function](https://github.com/nextcloud/desktop/blob/fe65715b975b3b3865fbc06151337072aa53467f/src/libsync/propagateupload.cpp#L685)
to 3 minutes per GB

**Comment by tobiasKaminsky** [comment]
Thanks for this hint!

**Comment by gomme600** [comment]
Adjusting the timeout seems like the best idea. This issue has been wreaking havok for quite a while for my videos uploads. I have almost 300gb of duplicate files!
