### ISSUE TITLE
Get access to Etag after at the end of an UploadFileRemoteOperation

### ISSUE THREAD

**Issue by vince-bourgmayer** [nextcloud/android-library#868]
Hello,

First of all, thanks for your work and your Library.
I'm looking for a way to read latest etag of a file after it has been uploaded with UploadFileRemoteOperation.

This could easily been read from HTTP's result header 
in https://github.com/nextcloud/android-library/blob/f0b28e537afcc113473783192c60fd13c573f30b/library/src/main/java/com/owncloud/android/lib/common/operations/RemoteOperationResult.java#L218

and 

https://github.com/nextcloud/android-library/blob/f0b28e537afcc113473783192c60fd13c573f30b/library/src/main/java/com/owncloud/android/lib/common/operations/RemoteOperationResult.java#L409

There is different way to do it but I guess the easiest one is to store those headers in a class field and provide a getHeaders() to access it.  The main issue I guess is to provide something generic to match with Apache Commons & OkHttp while you're migrating :-/

Edit:
Here is my proposal:
https://github.com/nextcloud/android-library/commit/415d824694a155eca4c3b724c16603002b0a316f

**Comment by TheScarastic** [comment]
@AlvaroBrey any insights if patch looks fine to you we could make a pull request

**Comment by vince-bourgmayer** [comment]
Pull request created:
https://github.com/nextcloud/android-library/pull/869

**Comment by AlvaroBrey** [comment]
> I'm looking for a way to read latest etag of a file after it has been uploaded with UploadFileRemoteOperation.

The correct way to do this is to have `UploadFileRemoteOperation`  save the required data  (in this case the etag) in `RemoteOperationResult.resultData`, and grab that `resultData` when needed.

Technically, `RemoteOperationResult` should abstract the details of HTTP requests and results from its clients, even though it does already expose `httpStatus` and  some location stuff. 

I can't really come up with use cases which could be solved by exposing the headers, but not by adding result data to the relevant operation, so my initial assesment of this is that it's not worth polluting the class.

**Comment by vince-bourgmayer** [comment]
Hi @AlvaroBrey,

Thanks for your feedback.
The way you suggest is the way I first thought to do it;

I also tried to extends the UploadFileRemoteOperation in my application with the will to just override
`protected RemoteOperationResult uploadFile(OwnCloudClient client) throws IOException` which is the only part I saw where I could read the etag.

But then I couldn't access mPutMethod because I'm not in the same package.
 Then I duplicated package name to get access to mPutMethod but I don't have access to the private static field of UploadFileRemoteOperation.
 
 Now I said that, I got an idea..

**Comment by AlvaroBrey** [comment]
> Hi @AlvaroBrey,
> 
> Thanks for your feedback. The way you suggest is the way I first thought to do it;
> 
> I also tried to extends the UploadFileRemoteOperation in my application with the will to just override `protected RemoteOperationResult uploadFile(OwnCloudClient client) throws IOException` which is the only part I saw where I could read the etag.
> 
> But then I couldn't access mPutMethod to read headers

No point in extending it; it should be modified here in the library. PRs welcome

**Comment by vince-bourgmayer** [comment]
@AlvaroBrey 

New Pull request as you suggested:
https://github.com/nextcloud/android-library/pull/870

**Comment by vince-bourgmayer** [comment]
@AlvaroBrey 
I apply your latest suggestion on UploadFileRemoteOperation.
#870

**Comment by vince-bourgmayer** [comment]
DCO fixed
