### ISSUE TITLE
Maven plugin needed?

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android-library#94]
https://github.com/nextcloud/android-library/blob/master/build.gradle#L12

Do we need this? 
@mario @AndyScherzinger

**Comment by AndyScherzinger** [comment]
I think it is used for jitpack.io but not 100% sure :/

**Comment by przybylski** [comment]
This allows to create a aar library which are distributed via maven.
There is no harm in keeping it. If anyone is fetching android-library with maven using aar theirs build will fail

**Comment by tobiasKaminsky** [comment]
Thanks for the explanation 👍
